---
title: Stephanie Slattery
timezone: UTC
collections:
  portfolio:
    title: Portfolio
    output: true
    permalink: "/portfolio/:path"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: stephanie.n.marx@gmail.com
description: 'Stephanie Slattery is a front end web developer based in Chicago and
  is definitely not made of bees.

'
baseurl: ''
url: http://stephanie.slattery.website
twitter_username: sublimemarch
github_username: stephmarx
markdown: kramdown
theme: minima
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
