---
new_page_extension: md
auto_deploy: true
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: _portfolio
  label: Portfolio
  create: all
  match: "**/*"
- type: jekyll-posts
  label: Posts
  create: all
  match: "**/*"
- type: directory
  path: _talks
  label: Talks
  create: all
  match: "**/*"
- type: directory
  path: _uploads
  label: Uploads
  create: all
  match: "**/*"
- type: jekyll-pages
  label: Pages
  create: all
upload_dir: img
public_path: "/img"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
